config/routes.rb
Rails.application.routes.draw do
  devise_for :teams
  root to: "teams#index"
  resources :teams, only: [:index, :show, :edit, :update] do
    resources :members
    resources :games, only: [:index, :create, :destroy] do
      resources :orders, only: [:new, :create, :show, :destroy]
      resources :batting_results, only: [:index, :create]
    end
    resources :rooms, only: [:index, :create, :destroy] do
      resources :messages, only: [:index, :create, :destroy]
    end
  end
  resources :games, only: [:index] do
    resources :results, only: [:index, :create, :update, :show]
  end
end

app/models/at_bat.rb
class AtBat < ApplicationRecord
  belongs_to :game
end

app/models/base_hist.rb
class BaseHist < ActiveHash::Base
  self.data = [
    { id: 1, name: '中学野球' },
    { id: 2, name: '高校野球' },
    { id: 3, name: '大学野球' },
    { id: 4, name: '実業団野球' }
  ]

  include ActiveHash::Associations
  has_many :members
end

app/models/dominant_hand.rb
class DominantHand < ActiveHash::Base
  self.data = [
    { id: 1, name: '右投/右打' },
    { id: 2, name: '右投/左打' },
    { id: 3, name: '右投/両打' },
    { id: 4, name: '左投/左打' },
    { id: 5, name: '左投/右打' },
    { id: 6, name: '左投/両打' }
  ]
  
  include ActiveHash::Associations
  has_many :members
end

app/models/field_error.rb
class FieldError < ActiveHash::Base
  self.data = [
    {id: 1, name: "内野失"},
    {id: 2, name: "外野失"},
    {id: 3, name: "捕失"},
  ]

  include ActiveHash::Associations
  has_many :batting_results
end

app/models/four_deadball.rb
class FourDeadball < ActiveHash::Base
  self.data = [
    {id: 1, name: "四球"},
    {id: 2, name: "死球"}
  ]

  include ActiveHash::Associations
  has_many :batting_results
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :team_games, dependent: :destroy
  has_many :teams, through: :team_games
  has_one :result, dependent: :destroy
  has_many :pitching_results, dependent: :destroy
  has_many :batting_results, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :at_bats, dependent: :destroy

  with_options presence: true do
    validates :game_day
    validates :game_time
    validates :stadium
    validates :address
  end
end

app/models/hit.rb
class Hit < ActiveHash::Base
  self.data = [
    {id: 1, name: "内野安"},
    {id: 2, name: "左安"},
    {id: 3, name: "中安"},
    {id: 4, name: "右安"},
    {id: 5, name: "右安"},
    {id: 6, name: "左2"},
    {id: 7, name: "中2"},
    {id: 8, name: "右2"},
    {id: 9, name: "左3"},
    {id: 10, name: "中3"},
    {id: 11, name: "右3"},
    {id: 12, name: "本塁打"},

  ]

  include ActiveHash::Associations
  has_many :batting_results
end

app/models/member.rb
class Member < ApplicationRecord
  before_validation :delete_space

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :position
  belongs_to :base_hist
  belongs_to :dominant_hand

  with_options presence: true do
    validates :name,     format: { with: /\A[ぁ-んァ-ヶ々一-龥]+\z/, message: 'にアルファベット・記号は使用できません' }, 
                         length: { minimum: 2, maximum: 8}

    validates :uni_no,     numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 100, only_integer: true}
    validates :dominant_hand
    validates :position_id

  end

  belongs_to :team
  has_many :batting_results
  has_one_attached :mem_image, dependent: :destoroy

  private
  def delete_space
    self.name = name.gsub(/[[:space:]]/,"") unless self.name.blank?
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :team

  validates :content, presence: true, unless: :format?
  
  with_options presence: true, unless: :message? do
    validates :game_day
    validates :game_time
    validates :stadium
    validates :address
  end

  private

  def format?
    self.game_day?
    self.game_time?
    self.stadium?
    self.address?
  end

  def message?
    self.content?
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :game
  belongs_to :team
  has_many :members
  has_many :batting_results
  
  with_options presence: true do 
    validates :position_id, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 10}
    validates :batting_order, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 9}
  end



end

app/models/out.rb
class Out < ActiveHash::Base
  self.data = [
    {id: 1, name: "三振"},
    {id: 2, name: "内ゴロ"},
    {id: 3, name: "内野飛"},
    {id: 4, name: "左飛"},
    {id: 5, name: "中飛"},
    {id: 6, name: "右飛"},
  ]

  include ActiveHash::Associations
  has_many :batting_results
end

app/models/point.rb
class Point < ActiveHash::Base
  self.data = [
    {id: 1, name: 1},
    {id: 2, name: 2},
    {id: 3, name: 3},
    {id: 4, name: 4}
  ]
  include ActiveHash::Associations
  has_many :batting_results
end

app/models/position.rb
class Position < ActiveHash::Base
  self.data = [
    { id: 1, name: '投手' },
    { id: 2, name: '捕手' },
    { id: 3, name: '一塁手' },
    { id: 4, name: '二塁手' },
    { id: 5, name: '三塁手' },
    { id: 6, name: '遊撃手' },
    { id: 7, name: '外野手' },
    { id: 8, name: 'レフト' },
    { id: 9, name: 'センター' },
    { id: 10, name: 'ライト' },
  ]

  include ActiveHash::Associations
  has_many :members
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :game

  with_options presence: true do
    validates :batting_first
    validates :fielding_first
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_teams, dependent: :destroy
  has_many :teams, through: :room_teams
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_team.rb
class RoomTeam < ApplicationRecord
  belongs_to :team
  belongs_to :room
end

app/models/team.rb
class Team < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_validation :delete_space

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :name, length: { in: 4..15 }, uniqueness: {case_sensitive: false }
    validates :rep_name, length: { minimum: 2, maximum: 8 }, format: { with: /\A[ぁ-んァ-ヶ々一-龥]+\z/ }
  end
  validates :password, 
      format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数字の混合で入力してください'},
      length: {minimum: 6, maximum: 10, message: 'は6文字以上10文字以下で設定してください'}

  has_many :members, dependent: :destroy

  has_many :room_teams
  has_many :rooms, through: :room_teams
  has_many :messages, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  has_many :team_games
  has_many :games, through: :team_games
  has_many :orders
  has_many :batting_results

  private
  def delete_space
    self.name = name.gsub(/[[:space:]]/,"") unless self.name.blank?
    self.rep_name = rep_name.gsub(/[[:space:]]/,"") unless self.rep_name.blank?
  end
end

app/models/team_game.rb
class TeamGame < ApplicationRecord
  belongs_to :team
  belongs_to :game
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :authenticate_team!
  before_action :team_match 

  def index
      @message = Message.new
      @rooms = Team.find(params[:team_id]).rooms
      @room = Room.find(params[:room_id])
      @messages = @room.messages.includes(:team)
  end

  def create
    @room = Room.find(params[:room_id])
    @message = @room.messages.new(message_params)
    if @message.valid?
      @message.save
      flash.now[:notice] = "メッセージが送信されました"
      redirect_to action: :index
    else
      @rooms = Team.find(params[:team_id]).rooms
      @messages = @room.messages.includes(:team)
      flash.now[:alert] = "メッセージの送信が失敗しました! 空白を無くしてください"
      render :index
    end
  end

  def destroy
    room = Room.find(params[:room_id])
    message = room.messages.find(params[:id])
    message.destroy
    flash[:alert] = "対戦申込を削除しました"
    redirect_to action: :index
  end

  private
  def team_match
    redirect_to root_path unless current_team.id == params[:team_id].to_i
  end

  def message_params
    params.require(:message).permit(:content, :game_day, :game_time, :stadium,:address,:room_id).merge(team_id: current_team.id)
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/messages/index.html.erb
<%= render "shared/main_header" %>
<div class="top-height"></div>

<div class="wrapper">
  <%# --- サイドバーの実装 --ここから--%>
  <div class="side-bar">
    <%= render "shared/sidebar" %>
  </div>
  <%# --- サイドバーの実装 ---ここまで-%>

  <%# --- チャット画面 ---ここから-%>
  <div class="chat">
    <%if flash[:alert] %>
      <p class="flash-message alert"><%= flash[:alert] %></p>
    <% elsif flash[:notice] %>
      <p class="flash-message notice"><%= flash[:notice] %></p>
    <%end%>

    <div class="messages" id="messages-height">
      <% @messages.each do |message|%>
        <div class="message message-container">
          <%if message.team != current_team%>
            <div class="upper-message">
          <%else%>
            <div class="upper-message right-box-upper">
          <%end%>
            <div class="message-icon">

              <%if message.team.image.attached?%>
                <%= image_tag message.team.image ,class: "room-icon"%>
              <%else%>
                <%= image_tag "noimage.png" ,class: "room-icon"%>
              <%end%>
            </div>
            <div class="message-date">
              <%= message.created_at.strftime("%Y年%m月%d日%H時%M分")%>
              <div class="message-user">
                <%= message.team.name%>
              </div>
            </div>
          </div>
          <div class="lower-container">
            <%if message.team != current_team %>
              <div class="lower-message">
                <%unless message.game_day.present? == true%>
                  <div class="message-content">
                    <%= message.content%> 
                  </div>
                <%else%>
                  <div class="format-display">
                    <p class="format-title">試合が申込まれました</p>
                    <p>◯試合予定日: <%= message.game_day.strftime("%Y年%m月%d日") %>(<%= %w(日 月 火 水 木 金 土)[message.game_day.wday] %>)</p>
                    <p>◯球場: <%= message.stadium %></p>
                    <p>◯球場住所: <%= message.address %></p>
                    <div class="offer-btn-container">
                      <%= form_with url: team_games_path(current_team.id), method: :post, local: :true do |f| %>
                        <%= f.hidden_field :game_day, value: message.game_day %>
                        <%= f.hidden_field :game_time, value: message.game_time %>
                        <%= f.hidden_field :stadium, value: message.stadium %>
                        <%= f.hidden_field :address, value: message.address %>
                        <%= hidden_field_tag "team_ids[]", message.room.teams.select{ |team| team.id != current_team.id}[0].id %>
                        <%= hidden_field_tag "team_ids[]", current_team.id %>
                        <%= f.submit "承諾", class: "offer-btn-left contract" %>
                      <%end%>
                      <%= link_to "辞退", team_room_message_path(current_team.id, message.room.id, message.id), method: :delete, data: {confirm: "#{message.room.teams.select{ |team| team.id != current_team.id}[0].name}からのオファーを辞退しますか？"} , class: "offer-btn" %>
                    </div>

                  </div>
                <%end%>
              </div>
            <%else%>
              <div class="lower-message right-box-lower">
                <%unless message.game_day.present? == true%>
                  <div class="message-content right">
                    <%= message.content%> 
                  </div>
                <%else%>
                  <div class="format-display">
                    <p class="format-title">試合の申込</p>
                    <p>◯試合予定日: <%= message.game_day.strftime("%Y年%m月%d日") %>(<%= %w(日 月 火 水 木 金 土)[message.game_day.wday] %>)</p>
                    <p>◯試合開始: <%= message.game_time.hour%>:<%= message.game_time.strftime("%M") %>~</p>
                    <p>◯球場: <%= message.stadium %></p>
                    <p>◯球場住所: <%= message.address %></p>
                    <div class="offer-btn-container">
                      <%= link_to "申込の取消", team_room_message_path(current_team.id, message.room.id, message.id), method: :delete, data: {confirm: "#{message.room.teams.select{ |team| team.id != current_team.id}[0].name}との試合申込を取り消しますか？"} , class: "offer-btn" %>
                    </div>
                  </div>
                <%end%>
              </div>
            <%end%>
            </div>
          </div>
      <%end%>
    </div>

    <%# ---タブの実装 ---ここから-%>
    <div class="tab-container">
      <ul class="tab-lists">
        <li id="tab1" class="active">
          <div class="tab-title">
            メッセージ
          </div>
        </li>
        <li id="tab2">
          <div class="tab-title">
            フォーム
          </div>
        </li>
      </ul>
      <div class="tab-content">
        <div class="tab-active"  id="tab1-cont">
          <%= form_with model: [@room, @message], url: team_room_messages_path(current_team.id, @room.id), method: :post, local: true, class: "form" do |f| %>
            <div class="form-input">
              <%= f.text_field :content ,class: "form-message", placeholder: "メッセージを入力" %>
            </div>
              <%= f.submit "送信" ,class: "form-submit" %>
          <%end%>
        </div>
        <div class="tab-none" id="tab2-cont">
          <%= form_with model: [@room, @message], url: team_room_messages_path(current_team.id, @room.id), method: :post, local: true, class: "format" do |f| %>
            <div class="input-gameday">
              <p>試合予定日</p><%= f.date_field :game_day, class: "game-day" %>
              <p>開始時間</p><%= f.time_select :game_time, {start_hour: 5, end_hour: 21, minute_step: 15, }  ,{class: "game-time"} %>
            </div>
            <div class="format-input">
              <%= f.text_field :stadium ,class: "format-message", placeholder: "球場名" %>
            </div>
            <div class="position">
              <div class="format-input">
                <%= f.text_field :address ,class: "format-message", placeholder: "球場の住所" %>
              </div>
                <%= f.text_field :content, style: "display: none;"%>
                <%= f.submit "送信" ,class: "form-submit format-submit" %>
            </div>
          <%end%>
        </div>
      </div>
    </div>
    <%# ---タブの実装  ---ここまで-%>
    
  </div>
</div>