config/routes.rb
Rails.application.routes.draw do
  devise_for :teams
  root to: "teams#index"
  resources :teams, only: [:index, :show, :edit, :update] do
    resources :members
    resources :games, only: [:index, :create, :destroy] do
      resources :orders, only: [:new, :create, :show, :destroy]
      resources :batting_results, only: [:index, :create]
    end
    resources :rooms, only: [:index, :create, :destroy] do
      resources :messages, only: [:index, :create, :destroy]
    end
  end
  resources :games, only: [:index] do
    resources :results, only: [:index, :create, :update, :show]
  end
end

app/models/at_bat.rb
class AtBat < ApplicationRecord
  belongs_to :game
end

app/models/base_hist.rb
class BaseHist < ActiveHash::Base
  self.data = [
    { id: 1, name: '中学野球' },
    { id: 2, name: '高校野球' },
    { id: 3, name: '大学野球' },
    { id: 4, name: '実業団野球' }
  ]

  include ActiveHash::Associations
  has_many :members
end

app/models/dominant_hand.rb
class DominantHand < ActiveHash::Base
  self.data = [
    { id: 1, name: '右投/右打' },
    { id: 2, name: '右投/左打' },
    { id: 3, name: '右投/両打' },
    { id: 4, name: '左投/左打' },
    { id: 5, name: '左投/右打' },
    { id: 6, name: '左投/両打' }
  ]
  
  include ActiveHash::Associations
  has_many :members
end

app/models/field_error.rb
class FieldError < ActiveHash::Base
  self.data = [
    {id: 1, name: "内野失"},
    {id: 2, name: "外野失"},
    {id: 3, name: "捕失"},
  ]

  include ActiveHash::Associations
  has_many :batting_results
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :team_games, dependent: :destroy
  has_many :teams, through: :team_games
  has_one :result, dependent: :destroy
  has_many :pitching_results, dependent: :destroy
  has_many :batting_results, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :at_bats, dependent: :destroy

  with_options presence: true do
    validates :game_day
    validates :game_time
    validates :stadium
    validates :address
  end
end

app/models/hit.rb
class Hit < ActiveHash::Base
  self.data = [
    {id: 1, name: "内野安"},
    {id: 2, name: "左安"},
    {id: 3, name: "中安"},
    {id: 4, name: "右安"},
    {id: 5, name: "右安"},
    {id: 6, name: "左2"},
    {id: 7, name: "中2"},
    {id: 8, name: "右2"},
    {id: 9, name: "左3"},
    {id: 10, name: "中3"},
    {id: 11, name: "右3"},
    {id: 12, name: "本塁打"},

  ]

  include ActiveHash::Associations
  has_many :batting_results
end

app/models/member.rb
class Member < ApplicationRecord
  before_validation :delete_space

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :position
  belongs_to :base_hist
  belongs_to :dominant_hand

  with_options presence: true do
    validates :name,     format: { with: /\A[ぁ-んァ-ヶ々一-龥]+\z/, message: 'にアルファベット・記号は使用できません' }, 
                         length: { minimum: 2, maximum: 8}

    validates :uni_no,     numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 100, only_integer: true}
    validates :dominant_hand
    validates :position_id

  end

  belongs_to :team
  has_many :batting_results
  has_one_attached :mem_image, dependent: :destoroy

  private
  def delete_space
    self.name = name.gsub(/[[:space:]]/,"") unless self.name.blank?
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :team

  validates :content, presence: true, unless: :format?
  
  with_options presence: true, unless: :message? do
    validates :game_day
    validates :game_time
    validates :stadium
    validates :address
  end

  private

  def format?
    self.game_day?
    self.game_time?
    self.stadium?
    self.address?
  end

  def message?
    self.content?
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :game
  belongs_to :team
  has_many :members
  has_many :batting_results
  
  with_options presence: true do 
    validates :position_id, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 10}
    validates :batting_order, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 9}
  end



end

app/models/out.rb
class Out < ActiveHash::Base
  self.data = [
    {id: 1, name: "三振"},
    {id: 2, name: "内ゴロ"},
    {id: 3, name: "内野飛"},
    {id: 4, name: "左飛"},
    {id: 5, name: "中飛"},
    {id: 6, name: "右飛"},
  ]

  include ActiveHash::Associations
  has_many :batting_results
end

app/models/point.rb
class Point < ActiveHash::Base
  self.data = [
    {id: 1, name: 1},
    {id: 2, name: 2},
    {id: 3, name: 3},
    {id: 4, name: 4}
  ]
  include ActiveHash::Associations
  has_many :batting_results
end

app/models/position.rb
class Position < ActiveHash::Base
  self.data = [
    { id: 1, name: '投手' },
    { id: 2, name: '捕手' },
    { id: 3, name: '一塁手' },
    { id: 4, name: '二塁手' },
    { id: 5, name: '三塁手' },
    { id: 6, name: '遊撃手' },
    { id: 7, name: '外野手' },
    { id: 8, name: 'レフト' },
    { id: 9, name: 'センター' },
    { id: 10, name: 'ライト' },
  ]

  include ActiveHash::Associations
  has_many :members
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :game

  with_options presence: true do
    validates :batting_first
    validates :fielding_first
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_teams, dependent: :destroy
  has_many :teams, through: :room_teams
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_team.rb
class RoomTeam < ApplicationRecord
  belongs_to :team
  belongs_to :room
end

app/models/team.rb
class Team < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_validation :delete_space

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :name, length: { in: 4..15 }, uniqueness: {case_sensitive: false }
    validates :rep_name, length: { minimum: 2, maximum: 8 }, format: { with: /\A[ぁ-んァ-ヶ々一-龥]+\z/ }
  end
  validates :password, 
      format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数字の混合で入力してください'},
      length: {minimum: 6, maximum: 10, message: 'は6文字以上10文字以下で設定してください'}

  has_many :members, dependent: :destroy

  has_many :room_teams
  has_many :rooms, through: :room_teams
  has_many :messages, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  has_many :team_games
  has_many :games, through: :team_games
  has_many :orders
  has_many :batting_results

  private
  def delete_space
    self.name = name.gsub(/[[:space:]]/,"") unless self.name.blank?
    self.rep_name = rep_name.gsub(/[[:space:]]/,"") unless self.rep_name.blank?
  end
end

app/models/team_game.rb
class TeamGame < ApplicationRecord
  belongs_to :team
  belongs_to :game
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseB</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="copy">
    Copyright Base_B 2021.<br>
    <span>Amateur Baseball Club</span>
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="header">
  <div class="header_container">
    <div class="header_logo"><a href="/">Base_B</a>
    </div>

    <%if team_signed_in? %>
      <ul class="header_lists">
        <li class="header_list_user">ログイン: <%= link_to current_team.name, team_path(current_team.id) ,class: "login-user" %></li>
        <li class="header_list"><%= link_to "ログアウト", destroy_team_session_path, method: :delete, class: "header-link" %></li>
        
      </ul>
    <%else%>
      <ul class="header_lists">
        <li class="header_list_user">ゲストさん</li>
        <li class="header_list"><%= link_to "ログインする", new_team_session_path ,class: "header-link" %></li>
        <li class="header_list"><%= link_to "新規登録", new_team_registration_path, class: "header-link" %></li>
      </ul>
    <%end%>
  </div>
</header>

app/views/shared/_main_header.html.erb
<header class="header">
  <div class="header_container">
    <div class="header_logo"><a href="/">Base_B</a>
    </div>

    <%if team_signed_in? %>
      <ul class="header_lists">
        <% if current_team.image.attached?%>
        <li class="header_list_user">ログイン:<%= image_tag current_team.image, class: "header-icon"%>
        <%else%>
        <li class="header_list_user">ログイン:<%= image_tag "noimage.png", class: "header-icon"%>
        <%end%>
           <%= link_to current_team.name, team_path(current_team.id) ,class: "login-user" %>
        </li>
        <li class="header_list"><%= link_to "ログアウト", destroy_team_session_path, method: :delete, class: "header-link" %></li>
      </ul>
    <%else%>
      <ul class="header_lists">
        <li class="header_list_user">ゲストさん</li>
        <li class="header_list"><%= link_to "ログインする", new_team_session_path ,class: "header-link" %></li>
        <li class="header_list"><%= link_to "新規登録", new_team_registration_path, class: "header-link" %></li>
      </ul>
    <%end%>
  </div>
</header>

app/views/shared/_sidebar.html.erb
<div class="rooms">
  <% @rooms.each do |room| %>
    <% away_team = room.teams.select{|team| team.id != current_team.id }[0]%> <%# away_teamに格納 %>
    <div class="room" id="room">
      <div class="room-name">
        <%if away_team.image.attached?%>
          <%= image_tag (away_team.image), class: "room-icon"%>
        <%else%>
          <%= image_tag "noimage.png" ,class: "room-icon"%>
        <%end%>
        <%= link_to away_team.name, team_room_messages_path(current_team.id, room.id), id: "room-color", class: "room-color" %>
      </div>
      <div class="d-button" style="display: none">
        <%= link_to "削除", team_room_path(current_team.id, room.id), method: :delete, data: {confirm: "ルームを削除してもいいですか？"},id:"dest-btn"%>
      </div>
    </div>
  <%end%>
</div>
<div class="destroy-call" id="dest-call">
  <div class="destroy-call-btn" id="call-btn">
    トークルームの削除
  </div>
</div>
 