config/routes.rb
Rails.application.routes.draw do
  devise_for :teams
  root to: "teams#index"
  resources :teams, only: [:index, :show, :edit, :update] do
    resources :members
    resources :games, only: [:index, :create, :destroy] do
      resources :orders, only: [:new, :create, :show, :destroy]
      resources :batting_results, only: [:index, :create]
    end
    resources :rooms, only: [:index, :create, :destroy] do
      resources :messages, only: [:index, :create, :destroy]
    end
  end
  resources :games, only: [:index] do
    resources :results, only: [:index, :create, :update, :show]
  end
end

app/models/at_bat.rb
class AtBat < ApplicationRecord
  belongs_to :game
end

app/models/base_hist.rb
class BaseHist < ActiveHash::Base
  self.data = [
    { id: 1, name: '中学野球' },
    { id: 2, name: '高校野球' },
    { id: 3, name: '大学野球' },
    { id: 4, name: '実業団野球' }
  ]

  include ActiveHash::Associations
  has_many :members
end

app/models/dominant_hand.rb
class DominantHand < ActiveHash::Base
  self.data = [
    { id: 1, name: '右投/右打' },
    { id: 2, name: '右投/左打' },
    { id: 3, name: '右投/両打' },
    { id: 4, name: '左投/左打' },
    { id: 5, name: '左投/右打' },
    { id: 6, name: '左投/両打' }
  ]
  
  include ActiveHash::Associations
  has_many :members
end

app/models/field_error.rb
class FieldError < ActiveHash::Base
  self.data = [
    {id: 1, name: "内野失"},
    {id: 2, name: "外野失"},
    {id: 3, name: "捕失"},
  ]

  include ActiveHash::Associations
  has_many :batting_results
end

app/models/four_deadball.rb
class FourDeadball < ActiveHash::Base
  self.data = [
    {id: 1, name: "四球"},
    {id: 2, name: "死球"}
  ]

  include ActiveHash::Associations
  has_many :batting_results
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :team_games, dependent: :destroy
  has_many :teams, through: :team_games
  has_one :result, dependent: :destroy
  has_many :pitching_results, dependent: :destroy
  has_many :batting_results, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :at_bats, dependent: :destroy

  with_options presence: true do
    validates :game_day
    validates :game_time
    validates :stadium
    validates :address
  end
end

app/models/hit.rb
class Hit < ActiveHash::Base
  self.data = [
    {id: 1, name: "内野安"},
    {id: 2, name: "左安"},
    {id: 3, name: "中安"},
    {id: 4, name: "右安"},
    {id: 5, name: "右安"},
    {id: 6, name: "左2"},
    {id: 7, name: "中2"},
    {id: 8, name: "右2"},
    {id: 9, name: "左3"},
    {id: 10, name: "中3"},
    {id: 11, name: "右3"},
    {id: 12, name: "本塁打"},

  ]

  include ActiveHash::Associations
  has_many :batting_results
end

app/models/member.rb
class Member < ApplicationRecord
  before_validation :delete_space

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :position
  belongs_to :base_hist
  belongs_to :dominant_hand

  with_options presence: true do
    validates :name,     format: { with: /\A[ぁ-んァ-ヶ々一-龥]+\z/, message: 'にアルファベット・記号は使用できません' }, 
                         length: { minimum: 2, maximum: 8}

    validates :uni_no,     numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 100, only_integer: true}
    validates :dominant_hand
    validates :position_id

  end

  belongs_to :team
  has_many :batting_results
  has_one_attached :mem_image, dependent: :destoroy

  private
  def delete_space
    self.name = name.gsub(/[[:space:]]/,"") unless self.name.blank?
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :team

  validates :content, presence: true, unless: :format?
  
  with_options presence: true, unless: :message? do
    validates :game_day
    validates :game_time
    validates :stadium
    validates :address
  end

  private

  def format?
    self.game_day?
    self.game_time?
    self.stadium?
    self.address?
  end

  def message?
    self.content?
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :game
  belongs_to :team
  has_many :members
  has_many :batting_results
  
  with_options presence: true do 
    validates :position_id, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 10}
    validates :batting_order, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 9}
  end



end

app/models/out.rb
class Out < ActiveHash::Base
  self.data = [
    {id: 1, name: "三振"},
    {id: 2, name: "内ゴロ"},
    {id: 3, name: "内野飛"},
    {id: 4, name: "左飛"},
    {id: 5, name: "中飛"},
    {id: 6, name: "右飛"},
  ]

  include ActiveHash::Associations
  has_many :batting_results
end

app/models/point.rb
class Point < ActiveHash::Base
  self.data = [
    {id: 1, name: 1},
    {id: 2, name: 2},
    {id: 3, name: 3},
    {id: 4, name: 4}
  ]
  include ActiveHash::Associations
  has_many :batting_results
end

app/models/position.rb
class Position < ActiveHash::Base
  self.data = [
    { id: 1, name: '投手' },
    { id: 2, name: '捕手' },
    { id: 3, name: '一塁手' },
    { id: 4, name: '二塁手' },
    { id: 5, name: '三塁手' },
    { id: 6, name: '遊撃手' },
    { id: 7, name: '外野手' },
    { id: 8, name: 'レフト' },
    { id: 9, name: 'センター' },
    { id: 10, name: 'ライト' },
  ]

  include ActiveHash::Associations
  has_many :members
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :game

  with_options presence: true do
    validates :batting_first
    validates :fielding_first
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_teams, dependent: :destroy
  has_many :teams, through: :room_teams
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_team.rb
class RoomTeam < ApplicationRecord
  belongs_to :team
  belongs_to :room
end

app/models/team.rb
class Team < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_validation :delete_space

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :name, length: { in: 4..15 }, uniqueness: {case_sensitive: false }
    validates :rep_name, length: { minimum: 2, maximum: 8 }, format: { with: /\A[ぁ-んァ-ヶ々一-龥]+\z/ }
  end
  validates :password, 
      format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数字の混合で入力してください'},
      length: {minimum: 6, maximum: 10, message: 'は6文字以上10文字以下で設定してください'}

  has_many :members, dependent: :destroy

  has_many :room_teams
  has_many :rooms, through: :room_teams
  has_many :messages, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  has_many :team_games
  has_many :games, through: :team_games
  has_many :orders
  has_many :batting_results

  private
  def delete_space
    self.name = name.gsub(/[[:space:]]/,"") unless self.name.blank?
    self.rep_name = rep_name.gsub(/[[:space:]]/,"") unless self.rep_name.blank?
  end
end

app/models/team_game.rb
class TeamGame < ApplicationRecord
  belongs_to :team
  belongs_to :game
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :authenticate_team!
  before_action :team_match

  def index
    @games = Team.find(params[:team_id]).games
  end

  def create
    @game = Game.new(game_params)
    if @game.valid?
      @game.save
      redirect_to action: :index
    else
      render "messages/index"
    end
  end

  private
  def team_match
    redirect_to root_path unless current_team.id == params[:team_id].to_i
  end
  
  def game_params
    params.permit(:game_day, :game_time, :stadium, :address, team_ids: [])
  end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/games/index.html.erb
<%= render "shared/main_header" %>
<div class="top-height"></div>
 
<%if flash[:alert] %>
  <p class="flash-message2 alert"><%= flash[:alert] %></p>
<% elsif flash[:notice] %>
  <p class="flash-message2 notice"><%= flash[:notice] %></p>
<%end%>

<div class="game-index-wrapper">
 
  <div class="game-index-container">
    <div class="game-index-title">
      <h1>試合日程画面</h1>
    </div>

    <%# --- ここからは試合の日程 ----  %>
    <% @games.each do |game|%>
      <% away_team = game.teams.select{|team| team != current_team}[0] %> <%# ログインチーム以外を away_teamに格納 %>
      <div class="game-card-wrapper">
        <div class="card-title">
          <p><%= game.game_day.strftime( "%Y年%m月%d日") %>(<%= %w(日 月 火 水 木 金 土)[game.game_day.wday] %>)</p>
        </div>
        <div class="game-card-upper-container">
          <div class="card-inner">      <%# --- カード左 %>        
            <% if current_team.image.attached? %>
              <%= image_tag current_team.image, class: "card-icon" %>
            <%else%>
              <%= image_tag "noimage.png", class: "card-icon" %>
            <%end%>
            <div class="card-team-name">
              <%= current_team.name%>
            </div>
          </div>
          <div class="card-middle">
            <p>対</p>
          </div>
          <div class="card-inner">      <%# --- カード右 %>
            <% if away_team.image.attached? %>
              <%= image_tag away_team.image, class: "card-icon" %>
            <%else%>
              <%= image_tag "noimage.png", class: "card-icon" %>
            <%end%>
              <div class="card-team-name">
                <%= link_to away_team.name, team_members_path(away_team.id) %> 
              </div>
          </div>
        </div>
        <div class="game-card-bottom-container">
          <p>開始時間：<%= game.game_time.strftime("%H時%M分")%></p>
          <p>球場：<%= game.stadium%></p>
          <p>住所：<%= game.address%></p>
        </div>
        <% unless current_team.orders.where(game_id: game.id).present? && away_team.orders.where(game_id: game.id).present? %> 
          <p class="caution">両チームのオーダー作成後に対戦画面が表示されます</p>
        <%end%>

        <div class="game-card-btn-container">
          <%# ------ オーダーボタンの条件分岐 %>
          <% if current_team.orders.where(game_id: game.id).present? %>
            <%= link_to "オーダー詳細", team_game_order_path(current_team.id, game.id, game.orders.where(team_id: current_team.id).ids), class:"game-card-btn orange" unless game.result.present?%>
          <% else %>
            <%= link_to "オーダー作成", new_team_game_order_path(current_team.id, game.id), class: "game-card-btn green" %>
          <% end %>

          <%# ------ 対戦ボタンの条件分岐 %>
          <%if game.result.present? && game.result.win.present?%>
            <%= link_to "試合結果", game_result_path(game.id, game.result.id), class: "game-card-btn  red"%>
          <% elsif game.result.present? %>
            <%= link_to "試合画面", team_game_batting_results_path(current_team.id, game.id), class: "game-card-btn  red" %>
          <% elsif current_team.orders.where(game_id: game.id).present? && away_team.orders.where(game_id: game.id).present? %>
            <%= link_to "対戦画面", game_results_path(game.id), class: "game-card-btn  red" %>
          <% end%>
        </div>
      </div>
    <%end%>
  </div>
</div>

<%= render 'shared/footer' %>