config/routes.rb
Rails.application.routes.draw do
  devise_for :teams
  root to: "teams#index"
  resources :teams, only: [:index, :show, :edit, :update] do
    resources :members
    resources :games, only: [:index, :create, :destroy] do
      resources :orders, only: [:new, :create, :show, :destroy]
      resources :batting_results, only: [:index, :create]
    end
    resources :rooms, only: [:index, :create, :destroy] do
      resources :messages, only: [:index, :create, :destroy]
    end
  end
  resources :games, only: [:index] do
    resources :results, only: [:index, :create, :update, :show]
  end
end

app/models/at_bat.rb
class AtBat < ApplicationRecord
  belongs_to :game
end

app/models/base_hist.rb
class BaseHist < ActiveHash::Base
  self.data = [
    { id: 1, name: '中学野球' },
    { id: 2, name: '高校野球' },
    { id: 3, name: '大学野球' },
    { id: 4, name: '実業団野球' }
  ]

  include ActiveHash::Associations
  has_many :members
end

app/models/dominant_hand.rb
class DominantHand < ActiveHash::Base
  self.data = [
    { id: 1, name: '右投/右打' },
    { id: 2, name: '右投/左打' },
    { id: 3, name: '右投/両打' },
    { id: 4, name: '左投/左打' },
    { id: 5, name: '左投/右打' },
    { id: 6, name: '左投/両打' }
  ]
  
  include ActiveHash::Associations
  has_many :members
end

app/models/field_error.rb
class FieldError < ActiveHash::Base
  self.data = [
    {id: 1, name: "内野失"},
    {id: 2, name: "外野失"},
    {id: 3, name: "捕失"},
  ]

  include ActiveHash::Associations
  has_many :batting_results
end

app/models/four_deadball.rb
class FourDeadball < ActiveHash::Base
  self.data = [
    {id: 1, name: "四球"},
    {id: 2, name: "死球"}
  ]

  include ActiveHash::Associations
  has_many :batting_results
end

app/models/game.rb
class Game < ApplicationRecord
  has_many :team_games, dependent: :destroy
  has_many :teams, through: :team_games
  has_one :result, dependent: :destroy
  has_many :pitching_results, dependent: :destroy
  has_many :batting_results, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :at_bats, dependent: :destroy

  with_options presence: true do
    validates :game_day
    validates :game_time
    validates :stadium
    validates :address
  end
end

app/models/hit.rb
class Hit < ActiveHash::Base
  self.data = [
    {id: 1, name: "内野安"},
    {id: 2, name: "左安"},
    {id: 3, name: "中安"},
    {id: 4, name: "右安"},
    {id: 5, name: "右安"},
    {id: 6, name: "左2"},
    {id: 7, name: "中2"},
    {id: 8, name: "右2"},
    {id: 9, name: "左3"},
    {id: 10, name: "中3"},
    {id: 11, name: "右3"},
    {id: 12, name: "本塁打"},

  ]

  include ActiveHash::Associations
  has_many :batting_results
end

app/models/member.rb
class Member < ApplicationRecord
  before_validation :delete_space

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :position
  belongs_to :base_hist
  belongs_to :dominant_hand

  with_options presence: true do
    validates :name,     format: { with: /\A[ぁ-んァ-ヶ々一-龥]+\z/, message: 'にアルファベット・記号は使用できません' }, 
                         length: { minimum: 2, maximum: 8}

    validates :uni_no,     numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 100, only_integer: true}
    validates :dominant_hand
    validates :position_id

  end

  belongs_to :team
  has_many :batting_results
  has_one_attached :mem_image, dependent: :destoroy

  private
  def delete_space
    self.name = name.gsub(/[[:space:]]/,"") unless self.name.blank?
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :room
  belongs_to :team

  validates :content, presence: true, unless: :format?
  
  with_options presence: true, unless: :message? do
    validates :game_day
    validates :game_time
    validates :stadium
    validates :address
  end

  private

  def format?
    self.game_day?
    self.game_time?
    self.stadium?
    self.address?
  end

  def message?
    self.content?
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :game
  belongs_to :team
  has_many :members
  has_many :batting_results
  
  with_options presence: true do 
    validates :position_id, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 10}
    validates :batting_order, numericality: {greater_than_or_equal_to: 1, less_than_or_equal_to: 9}
  end



end

app/models/out.rb
class Out < ActiveHash::Base
  self.data = [
    {id: 1, name: "三振"},
    {id: 2, name: "内ゴロ"},
    {id: 3, name: "内野飛"},
    {id: 4, name: "左飛"},
    {id: 5, name: "中飛"},
    {id: 6, name: "右飛"},
  ]

  include ActiveHash::Associations
  has_many :batting_results
end

app/models/point.rb
class Point < ActiveHash::Base
  self.data = [
    {id: 1, name: 1},
    {id: 2, name: 2},
    {id: 3, name: 3},
    {id: 4, name: 4}
  ]
  include ActiveHash::Associations
  has_many :batting_results
end

app/models/position.rb
class Position < ActiveHash::Base
  self.data = [
    { id: 1, name: '投手' },
    { id: 2, name: '捕手' },
    { id: 3, name: '一塁手' },
    { id: 4, name: '二塁手' },
    { id: 5, name: '三塁手' },
    { id: 6, name: '遊撃手' },
    { id: 7, name: '外野手' },
    { id: 8, name: 'レフト' },
    { id: 9, name: 'センター' },
    { id: 10, name: 'ライト' },
  ]

  include ActiveHash::Associations
  has_many :members
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :game

  with_options presence: true do
    validates :batting_first
    validates :fielding_first
  end
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :room_teams, dependent: :destroy
  has_many :teams, through: :room_teams
  has_many :messages, dependent: :destroy

  validates :name, presence: true
end

app/models/room_team.rb
class RoomTeam < ApplicationRecord
  belongs_to :team
  belongs_to :room
end

app/models/team.rb
class Team < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  before_validation :delete_space

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :name, length: { in: 4..15 }, uniqueness: {case_sensitive: false }
    validates :rep_name, length: { minimum: 2, maximum: 8 }, format: { with: /\A[ぁ-んァ-ヶ々一-龥]+\z/ }
  end
  validates :password, 
      format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'は半角英数字の混合で入力してください'},
      length: {minimum: 6, maximum: 10, message: 'は6文字以上10文字以下で設定してください'}

  has_many :members, dependent: :destroy

  has_many :room_teams
  has_many :rooms, through: :room_teams
  has_many :messages, dependent: :destroy
  has_one_attached :image, dependent: :destroy
  has_many :team_games
  has_many :games, through: :team_games
  has_many :orders
  has_many :batting_results

  private
  def delete_space
    self.name = name.gsub(/[[:space:]]/,"") unless self.name.blank?
    self.rep_name = rep_name.gsub(/[[:space:]]/,"") unless self.rep_name.blank?
  end
end

app/models/team_game.rb
class TeamGame < ApplicationRecord
  belongs_to :team
  belongs_to :game
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :authenticate_team!, except: [:index, :show]
  before_action :member_match, only: [:edit, :update, :destroy]

  def index
    @team = Team.find(params[:team_id])
    @room = Room.new
    @members = @team.members.order(position_id: "ASC")
  end

  def new
    @member = Member.new
    @team = Team.find(params[:team_id])
  end

  def create
    @member = Member.new(member_params)
    if @member.save
      flash[:notice] = "#{@member.name}選手の登録が完了しました"
      redirect_to action: :index
    else
      @team = Team.find(params[:team_id])
      flash[:alert] = "選手の登録ができませんでした"
      render action: :new
    end
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    # member_matchで インスタンスの生成・チームのオーナーのみ編集可能
  end

  def update
    # member_matchで インスタンスの生成・チームのオーナーのみ更新可能

    if @member.update(member_params)
      redirect_to team_member_path(@member.team_id, @member.id)
    else
      render action: :edit
    end
  end

  def destroy
    # member_matchで インスタンスの生成・チームのオーナーのみ削除可能
    if @member.destroy
      redirect_to team_members_path( params[:team_id])
    end
  end
  

  private
  
  def member_match
    @member = Member.find(params[:id])
    redirect_to team_members_path(@member.team_id) unless current_team.id == @member.team_id
  end

  
  def member_params
    params.require(:member).permit(:name, :uni_no, :dominant_hand_id, :position_id, :base_hist_id,
      :mem_image).merge(team_id: current_team.id)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/members/edit.html.erb
<%= render "shared/main_header" %>

<div class="show-main-wrapper">
<div class="top-height"></div>
  <div class="new-container">
    <div class="field-container">
    <h2 class="title">選手編集 : <%= @member.team.name %></h2>
      <%= form_with model: @member, url: team_member_path(@member.team_id, @member.id), method: :put,  local: true do |f|%>
        <div class='field-input'>
          選手名を入力<i> ＊空白を含めない＊</i>
        </div>
        <div class='field-input'>
          <%= f.text_field :name, placeholder: "入力例 : 田中太郎" %>
        </div>
        <div class='field-input'>
          写真を登録
        </div>
        <div class='field-input'>
          <%= f.file_field :mem_image, class: "image-input" %>
        </div>
        <div class='field-input'>
          <span class="span-form-label">背番号入力</span>
          <%= f.text_field :uni_no, placeholder: "0 ~ 100", class: "select-input"%>
          <span class="span-form-label">番</span>
        </div>
        <div class='field-input'>
        <span class="span-form-label">利投・利打</span>
          <%= f.collection_select :dominant_hand_id, DominantHand.all, :id, :name, { include_blank: "----"}, class: "select-input" %>
        </div>
        <div class='field-input'>
          <span class="span-form-label">ポジション</span>
          <%= f.collection_select :position_id, Position.where(id: [1,2,3,4,5,6,7]), :id, :name, {include_blank: "----"}, class: "select-input" %>
        </div>
        <div class='field-input'>
          <span class="span-form-label">最終野球歴</span>
          <%= f.collection_select :base_hist_id, BaseHist.all, :id, :name, {include_blank: "----"}, class: "select-input"  %>
        </div>
        <div class='actions'>
          <%= f.submit "選手登録", class: "submit-btn" %>
        </div>
      <%end%>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/members/index.html.erb
<%= render "shared/main_header" %>

<div class="top-height"></div>
  <%if flash[:notice] %>
    <p class="flash-message2 notice"><%= flash[:notice] %></p>
  <%end%>
<div class="mem-index-main-wrapper">
  <div class="mem-index-container">
    <div class="team-name"><%= @team.name %></div>
    <div class="image-container">
      <% if @team.image.attached? %>
        <%= image_tag @team.image.variant(resize: "180x160"), class: "team-logo" %>
      <%else%>
        <%= image_tag "noimage.png", class: "team-logo" %>  <%#画像がなければデフォルト画像の表示 %>
      <%end%>
    </div>

    <% if team_signed_in? && current_team.id == @team.id %>
      <div class="index-btn-container">
        <%= link_to "選手の追加", new_team_member_path(@team.id), class:"index-btn" %>
      </div>
    <%elsif team_signed_in? %>
      <div class="index-btn-container">
        <%= form_with model: @room, url: team_rooms_path(current_team), method: :post, local: :true do |f| %>
          <%= f.hidden_field :name, value: @team.name %>

          <select name="room[team_ids][]" class="hidden">
            <option value=<%=@team.id%> class="hidden"><%=@team.name%> </option>
          </select>
          
          <input name="room[team_ids][]" type="hidden" value=<%= current_team.id%>> 
          <%= f.submit "対戦申し込み", class:"index-btn" %>
        <%end%>
      </div>
    <%end%>

    <div class="team-grades">
      <div>対戦回数  <%=Result.where(win: @team.name).count + Result.where(lose: @team.name).count %></div>
      <div><%=Result.where(win: @team.name).count%>勝 <%= Result.where(lose: @team.name).count%>敗</div>
      <div>チーム打率 <%= sprintf("%.3f", (@team.batting_results.count(:hit_id).to_f / @team.batting_results.count).round(3) )%></div>
      <div>チーム奪三振数</div>
      <div>高校野球出身者</div>
    </div>
    

    <div class="mem-container">
        <div class="mem-pitcher">
          <h2>投手一覧</h2>
            <% @members.each do |member|%>
              <% if member.position_id == 1 %>
                <div class="person-container">
                  <% if member.mem_image.attached? %>
                    <%= link_to image_tag(member.mem_image, class: "person-image"), team_member_path(@team.id, member.id)  %>
                  <%else%>
                    <%= link_to image_tag("noimage.png", class: "person-image"), team_member_path(@team.id, member.id)  %>
                  <%end%>
                  <div class="person-profile-left">
                    <div class="profile-tag">
                      No: <%= member.uni_no %>
                    </div>
                    <div class="profile-tag">
                      <%= member.name%>
                    </div>
                    <div class="profile-tag">
                      <%= member.position.name %>
                    </div>
                    <div class="profile-tag">
                      <%= member.dominant_hand.name %>
                    </div>
                  </div>
                  <div class="person-profile-right">
                    <div class="profile-tag">
                      登板回数
                    </div>
                    <div class="profile-tag">
                      7勝 2敗
                    </div>
                    <div class="profile-tag">
                      奪三振数
                    </div>
                    <div class="profile-tag">
                      四球 20/死球 5
                    </div>
                    <div class="profile-tag">
                      被安打
                    </div>
                  </div>
                </div>
              <%end%>
            <%end%>
        </div>

        <div class="mem-batter">
          <h2>打者一覧</h2>
          <% @members.each do |member|%>
          <% unless member.position_id == 1 %>
            <div class="person-container">
              <% if member.mem_image.attached? %>
                <%= link_to image_tag(member.mem_image, class: "person-image"), team_member_path(@team.id, member.id)  %>
              <%else%>
                <%= link_to image_tag("noimage.png", class: "person-image"), team_member_path(@team.id, member.id)  %>
              <%end%>

              <div class="person-profile-left">
                <div class="profile-tag">
                  No: <%= member.uni_no %>
                </div>
                <div class="profile-tag">
                  <%= member.name%>
                </div>
                <div class="profile-tag">
                  <%= member.position.name %>
                </div>
                <div class="profile-tag">
                  <%= member.dominant_hand.name %>
                </div>
              </div>
              <div class="person-profile-right">
                <div class="profile-tag">
                  打率 <%= sprintf("%.3f", (member.batting_results.count(:hit_id).to_f / member.batting_results.count).round(3))%>
                </div>
                <div class="profile-tag">
                  打席数 <%= member.batting_results.count %>
                </div>
                <div class="profile-tag">
                  打点 <%= member.batting_results.sum(:point_id) %>
                </div>
                <div class="profile-tag">
                  本塁打 <%= member.batting_results.where(hit_id: 12).count %>
                </div>
              </div>
            </div>
          <%end%>
          <%end%>
        </div>
      </div>
  </div>
</div>





<%= render 'shared/footer' %>

app/views/members/new.html.erb
<%= render "shared/main_header" %>

<div class="top-height"></div>
<div class="show-main-wrapper">

  <%if flash[:alert] %>
    <p class="flash-message2 alert"><%= flash[:alert] %></p>
  <%end%>

  <div class="new-container">
    <div class="field-container">
      <h2 class="title">選手登録 : <%= @team.name %></h2>
      <% if @member.errors.any? %>
        <div class="member-errors-container">
          <%= render "devise/shared/error_messages", resource: @member%>
        </div>
        <%end%>
      <%= form_with model: @member, url: team_members_path(@team.id), method: :post,  local: true do |f|%>
        <div class='field-input'>
          選手名を入力<i> ＊空白を含めない＊</i>
        </div>
        <div class='field-input'>
          <%= f.text_field :name, placeholder: "入力例 : 田中太郎" , maxlength: 8%>
        </div>
        <div class='field-input'>
          写真を登録
        </div>
        <div class='field-input'>
          <%= f.file_field :mem_image, class: "image-input" %>
        </div>
        <div class='field-input'>
          <span class="span-form-label">背番号入力</span>
          <%= f.number_field :uni_no, placeholder: "1 ~ 100", maxlength: 3,class: "select-input"%>
          <span class="span-form-label">番</span>
        </div>
        <div class='field-input'>
        <span class="span-form-label">利投・利打</span>
          <%= f.collection_select :dominant_hand_id, DominantHand.all, :id, :name, { include_blank: "----"}, class: "select-input" %>
        </div>
        <div class='field-input'>
          <span class="span-form-label">ポジション</span>
          <%= f.collection_select :position_id, Position.where(id: [1,2,3,4,5,6,7]), :id, :name, {include_blank: "----"}, class: "select-input" %>
        </div>
        <div class='field-input'>
          <span class="span-form-label">最終野球歴</span>
          <%= f.collection_select :base_hist_id, BaseHist.all, :id, :name, {include_blank: "----"}, class: "select-input"  %>
        </div>
        <div class='actions'>
          <%= f.submit "選手登録", class: "submit-btn" %>
        </div>
      <%end%>
    </div>
  </div>
</div>

<%= render 'shared/footer' %>

app/views/members/show.html.erb
<%= render "shared/main_header" %>

<div class="show-main-wrapper">
  <div class="top-height"></div>
  <div class="show-container">
    <div class="profiles">
      <% if @member.mem_image.attached? %>
        <%= image_tag @member.mem_image.variant(resize: "200x180"), class: "team-logo" %>
      <%else%>
        <%= image_tag "noimage.png", class: "team-logo" %>  <%#画像がなければデフォルト画像の表示 %>
      <%end%>
      <% if team_signed_in? && current_team.id == @member.team_id %>
        <div class="btn-container">
          <%= link_to "選手編集", edit_team_member_path(@member.team_id, @member.id), class: "show-btn member-edit" %>
          <%= link_to "選手削除", team_member_path(@member.team_id, @member.id), method: :delete, data: {confirm: '削除しますか?' }, class: "show-btn delete-edit" %>
        </div>
        <div class="btn-container">
          <%= link_to "選手一覧", team_members_path(@member.team_id), class: "show-btn member-index" %>
        </div> 
      <%else%>
        <div class="btn-container">
          <%= link_to "選手一覧", team_members_path(@member.team_id), class: "show-btn member-index" %>
        </div> 
      <%end%>
      <div class="profile">
        <div class="left-pro">
          選手名:
        </div>
        <div class="right-pro">
          <%= @member.name %>
        </div>
      </div>
      <div class="profile">
        <div class="left-pro">
          ポジション:
        </div>
        <div class="right-pro">
          <%= @member.position.name %>
        </div>
      </div>
      <div class="profile">
        <div class="left-pro">
          背番号:
        </div>
        <div class="right-pro">
          <%= @member.uni_no %>
        </div>
      </div>
      <div class="profile">
        <div class="left-pro">
          投打:
        </div>
        <div class="right-pro">
          <%= @member.dominant_hand.name %>
        </div>
      </div>
      <div class="profile">
        <div class="left-pro">
          野球部歴:
        </div>
        <div class="right-pro">
          <%= @member.base_hist.name %>
        </div>
      </div>
    </div>  
  </div>
</div>

<%= render 'shared/footer' %>